django-web-app/api/urls.py
from django.urls import path
from .views import GenerateTokenView, AnalyzeURLView, TaskStatusView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('generate-token/', GenerateTokenView.as_view(), name='generate_token'),
    path('analyze-url/', AnalyzeURLView.as_view(), name='analyze_url'),
    path('task-status/<str:task_id>/', TaskStatusView.as_view(), name='task_status'),
]

django-web-app/cogniguard/urls.py
"""
URL configuration for cogniguard project.

"""
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

# sitemap
from .sitemap import StaticViewSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'static': StaticViewSitemap,
}


# Admin panel customization
admin.site.site_header = "CogniGuard Admin"
admin.site.site_title = "CogniGuard Admin Portal"


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("", include("home.urls")),

    # for rendering reset password cnf template
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),

    # ensuring password reset completed successfully
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),

    path('accounts/', include('allauth.urls')), # all OAuth operations will be performed 

     # api urls
    path("api/", include("api.urls")),
     
     # sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]
# # vercel deployment url configuration

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# custom 404 page 
handler404 = 'home.views.handler404'

django-web-app/home/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views

from django.views.generic import RedirectView
from home.views import ResetPasswordView

app_name="home"

urlpatterns = [
    path("", views.index, name="home"),
    path("faqs/", views.faqs, name="faqs"),
    path("report-dp/", views.reportDp, name="report-dp"),
    path("about/", views.about, name="about"),
    path("terms-conditions/", views.termsConditions, name="terms-conditions"),
    path("know-about-dp/", views.knowAboutDp, name="know-about-dp"),
    path("login/", views.loginUser, name="loginUser"),
    path("register/", views.registerUser, name="registerUser"),
    path("detected-dp/", views.detected_dp, name="detected-dp"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("logout/", views.logoutUser, name="logoutUser"),
    path("verify-email/", views.verifyEmail, name="verify-email"),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('health-check/', views.health_check, name='health_check'),
    path('privacy-policy/', views.privacyPolicy, name='privacy-policy'),
    path('terms-of-use/', views.termsOfUse, name='terms-of-use'),
    path('generate-token/', views.generate_token, name='generate_token'),
    path('create-api-key/', views.create_api_key, name='create_api_key'),
    path('delete-api-key/<int:key_id>/', views.delete_api_key, name='delete_api_key'),

    
]

django-web-app/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static "css/about.css" %}">
{% endblock head %}

{% block title %}About{% endblock title %}

{% block content %}
{% include 'messages.html' %}
<div>
    <section class="description">
        <h2>What is CogniGuard?</h2>
        <div class="description-sub">
            <img src="{% static 'img/cogniguard-popup.png' %}" alt="Image">
            <div>
                <p>CogniGuard is a powerful web extension designed to empower users by identifying and combatting dark patterns on various websites, particularly focusing on E-commerce platforms. Ensuring users a transparent and ethical online experience.</p>
                <a target="_blank" href="https://github.com/4darsh-Dev/CogniGaurd/" class="download-btn"><i class="fab fa-chrome"></i> Download for Chrome</a>
                
            </div>
        

        </div>
        
    </section>
    <section class="features">
        <h2>Features</h2>
        <div class="grid-container">
            <div class="feature-box">
                <h3>Transparency Score</h3>
                <p>This web extension is powered by Fine-Tuned Deep Learning model BERT for classifiying dark patterns.</p>
                <p>Provides Transparency score for websites. </p>
            </div>
            <div class="feature-box">
                <h3>Dark Pattern Detection</h3>
                <p>Dark Pattern it detects: Urgency, Scarcity, Misdirection, Social-Proof, Obstruction, Sneaking, Forced Action + Not Dark Pattern.</p>
                <a href="#" class="download-btn">Know More</a>
            </div>
        </div>
    </section>
    <section class="subscription">
        <h2>Freemium Subscription Model</h2>
        <div class="grid-container">
            <div class="feature-box">
                <h3>Free Features</h3>
                <ul>
                    <li>Basic dark pattern detection</li>
                    <li>Weekly reports</li>
                    <li>Access to community forum</li>
                </ul>
            </div>
            <div class="feature-box">
                <h3>Premium Features</h3>
                <ul>
                    <li>Advanced dark pattern detection</li>
                    <li>24x7 non-stop service</li>
                    <li>Website transparency scores</li>
                    <li>Priority support</li>
                    <li>Advanced search</li>
                </ul>
                <button onclick="redirectToPayment()">Upgrade Now</button>
            </div>
        </div>
    </section>
    <section class="download">
        <h2>Download CogniGuard</h2>
        <div class="grid-container">
            <div class="feature-box">
                <h3>Version 1.0</h3>
                <p>Released Stable</p>
                <a target="_blank" href="https://github.com/4darsh-Dev/CogniGaurd/" class="download-btn"><i class="fab fa-chrome"></i> Download for Chrome</a>
            </div>
            <div class="feature-box">
                <h3>Version 2.0</h3>
                <p>In Progress</p>
                <button style="background-color: #333;" disabled >Coming Soon</button>
            </div>
        </div>
    </section>

</div>
{% endblock content %}

{% block script %}
<script src="{% static "js/about.js"%}"></script>
<script src="{% static 'js/messages.js' %}"></script>
{% endblock script %}

django-web-app/templates/custom_404.html
{% extends "base.html" %}
{% load static %}
{% block title %}Page Not Found{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/custom_404.css' %}">
<script src="https://cdn.tailwindcss.com"></script>
{% endblock head %}

{% block content %}

{% include 'messages.html' %}


<div className="flex h-[100dvh] flex-col items-center justify-center space-y-6 px-4 text-center">
    <div className="space-y-2">
      <div className="flex items-center justify-center">
        <img src="{% static 'img/404.png' %}" alt="404" className="w-56 h-56">
      </div>
      <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Oops! Page Not Found</h1>
      <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
        The page you are looking for could not be located. Please check the URL or try navigating back to the homepage.
      </p>
      <button className="px-4 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-800 transition-all duration-300">
          <a href="{% url 'home:home' %}">Return to Home</a>
      </button>
    </div>
  </div>
{% endblock content %}



{% block script %}

<script src="{% static 'js/messages.js' %}"></script>

{% endblock script %}

django-web-app/templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static "css/dashboard.css" %}">
{% endblock head %}

{% block title %}Dashboard{% endblock title %}

{% block content %}

{% include 'messages.html' %}

<div class="dashboard-container">
    <h1>Welcome, {{ username }}!</h1>
    <div class="token-section">
        <h2>API Token</h2>
        <div id="token-display">
            <p>Your API token: <span id="token">Not generated</span></p>
        </div>
        <button id="generate-token">Generate New Token</button>
        <button id="copy-token" disabled>Copy Token</button>
    </div>
    <token-list></token-list>
    <div class="instructions">
        <h3>How to use your token:</h3>
        <ol>
            <li>Generate a new token using the button above.</li>
            <li>Copy the token and keep it secure.</li>
            <li>Insert the token in your CogniGuard web extension.</li>
            <li>The token will be used for authenticating API requests.</li>
        </ol>
    </div>
    <a href="{% url 'home:logoutUser' %}" class="logout-btn">Logout</a>
</div>



{% endblock content %}

{% block script %}

 <script src="{% static "js/messages.js" %}"></script> 
 <script src="{% static "js/dashboard.js" %}"></script> 

{% endblock script %}

django-web-app/templates/detected_dp.html
{% extends "base.html" %}

{% load static %}

{% block title %}Search Dark Patterns | Detected Dark Patterns{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static "css/detected_dp.css" %}">
{% endblock head %}

{% block content %}

{% include 'messages.html' %}

<div class="dp-search-box">
    <div class="dp-header">
        <h1>Detected <span>Dark Patterns</span></h1>
        <p>Search for websites that have been found using dark patterns.</p>
    </div>
    
    <div class="search-container">
        <!-- <h1>Search For Dark Patterns</h1> -->
        <input type="text" id="search-input" placeholder="Enter website name or URL">
        <div id="suggestions" class="suggestions"></div>
        <div id="results" class="results"></div>
    </div>
</div>

{% endblock content %}


{% block script %}
<script src="{% static "js/detected_dp.js" %}"></script>
<script src="{% static 'js/messages.js' %}"></script>

{% endblock script %}

django-web-app/templates/faqs.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static "css/faqs.css" %}">
{% endblock head %}

{% block title %}FAQs{% endblock title %}

{% block content %}

{% include 'messages.html' %}

<div class="content-container">


    <section class="content-section">
        <section class="faqs-heading font-secondary">
            <!-- <h1 class="font-mid-large">Need Help?</h1> -->
            <h1 class="font-mid-large">Welcome to <span class="blue-text">CogniGuard</span> Help Center</h1>
            <h2 class="font-medium">Clarity beyond Words</h2>
        </section>
        <section class="faqs-section">
            <h1 class="font-medium font-secondary">FAQs</h1>
            <div class="faqs">
                <div class="faqs-div">
                    {% if faqs %}
    
                    {% for faq in faqs %}
                    <div class="faq">
                        <div class="faq-question">
                            <span class="material-symbols-outlined">adjust</span>
                            <span class="faq-ques-text">{{ faq.question }}</span>
                            <i class="material-symbols-outlined faq-button">expand_more</i>
                        </div>
                        <div class="faq-answer hide" id="faq1-content">
                            <p> {{ faq.answer}} </p>
                        </div>
                    </div>
    
                    {% endfor %}
    
                    {% endif %}
    
                   
                </div>
            </div>
        </section>
    </section>
    <br><br>
</div>

{% endblock content %}

{% block script %}

<script src="{% static "js/faqs.js" %}"></script>
<script src="{% static 'js/messages.js' %}"></script>

{% endblock script %}

django-web-app/templates/index.html
{% extends "base.html" %}
 {% load static %}
 {% block head %}{% endblock head %}

 {% block title %}Home{% endblock title %}

{% block content %}

{% include 'messages.html' %}

<div class="preloader4">
  <div class="loader">
    <div class="ring"></div>
    <div class="ring"></div>
    <div class="ring"></div>
    <p>CogniGuard</p>
  </div>
</div>

<section class="content-section">
    <section class="elastic-section">
        <div class="container-first">
          <div class="logo-container">
            <img src="{% static 'img/cogniguard-logo.png' %}" alt="CogniGaurd" class="home-logo">
            <span>CogniGuard</span>
          </div>
          <h1 class="title">Your Shield against <span class="highlight">Dark Patterns</span></h1>
          <p class="description">
            CogniGuard is a powerful web-extension which is capable of detecting Dark Patterns on E-commerce websites. Powered by Fine-Tuned Deep Learning Models for classifcation tasks on large and contextual datasets, CogniGuard is your shield against deceptive practices.
          </p>
          <div class="cta-container">
            <a href="{% url 'home:registerUser' %}" class="btn btn-primary">Start free trial</a>
            <a target="_blank" href="https://www.youtube.com/watch?v=1DoYa1wVWhA&t=8s&ab_channel=AdarshGeeksLab" class="btn btn-secondary">
              YouTube Demo <i class="fas fa-arrow-right"></i>
            </a>
          </div>
          <a target="_blank" href="https://github.com/4darsh-Dev/CogniGaurd" class="download-link"><i fab fa-chrome></i>Download for Chrome</a>
        </div>
        <div class="shape shape-1"></div>
        <div class="shape shape-2"></div>
        <div class="shape shape-3"></div>
      </section>


      <section class="scalability-section">
        <div class="container-second">
          <div class="content">
            <h2 class="subtitle">SCALABILITY</h2>
            <h1 >Run it on any Web Browser. Chrome, Firefox, Safari, Edge </h1>
            <p class="description">
              Navigate to the Web-Extension Section of your browser. Select CogniGuard and click on Analyze Button It will start crunching Fresh Data from our Servers. Response in almost not time.
            </p>
            <p class="description">
              It scales horizontally to handle kajillions of events per second, while automatically managing how to handle mutliple requests per second with ease.
            </p>
          </div>
          <div class="visual">
            <div class="hexagon">
              <div class="laptop-icon"></div>
            </div>
            <div class="server server-1"></div>
            <div class="server server-2"></div>
            <div class="server server-3"></div>
            <div class="server server-4"></div>
            <div class="server server-5"></div>
            <div class="particle particle-1"></div>
            <div class="particle particle-2"></div>
            <div class="particle particle-3"></div>
            <div class="particle particle-4"></div>
          </div>
        </div>
      </section>


      <section class="flexibilty-section">
        <div class="text-content">
            <h2>FLEXIBILITY</h2>
            <h1>Easy Setup and Personalized Support</h1>
            <p> Dedicated user Dashboard for Personalized support, Where your can manage your API Keys and Browse through your requests and responses.  <a href="{% url 'home:report-dp' %}">Reporting Dark Patterns </a> made easy. Submit your contribution 💗 to our Crowdsourced database and earn Community Reward Points ⭐. </p>
        </div>
        <div class="image-content">
            <img src="{% static 'img/flexibility-img.png' %}" alt="flexibility-img">
        </div>
        <div class="animated-shapes">
            <i class="fas fa-circle"></i>
            <i class="fas fa-square"></i>
            <i class="fas fa-triangle"></i>
        </div>
    </section>

    <section class="esre-section">
      <div class="esre-content">
          <img src="{% static 'img/brain-waves-img.png' %}" alt="Brain Illustration" class="esre-illustration">
          <div class="esre-text">
              <h1>Dive deeper into CogniGaurd Working</h1>
              <p>
                  <a href="#" class="esre-link">The CogniGuard Backend API</a>™ (DRF) is powered by Fine-Tuned Large Language Models (LLMs) based on the transformer architecture form HuggingFace Hub Family of Open Source LLMs.
                  For Object Detection we use Convolutional Neural Networks (CNNs) and Beautiful Soup for Web Scraping.
                  <br>
                  Interested in the technical details? <a target="_blank" href="https://github.com/4darsh-Dev/CogniGaurd/wiki" class="esre-link">Read the CogniGuard documentation</a>.
              </p>
          </div>
      </div>
      <div id="animated-shapes">
        <div class="shape-esre"></div>
        <div class="shape-esre"></div>
        <div class="shape-esre"></div>
        <div class="shape-esre"></div>
      </div>
  </section>

  <!-- testiomonial section  -->

  <section class="testimonial-section">
    <div class="testimonial-header">
        <h2>CogniGuard reviews</h2>
        <p>What our users are saying...</p>
    </div>
    <div class="testimonial-cards">
        <div class="testimonial-card">
            <i class="fas fa-quote-left"></i>
            <p>I love how CogniGuard educates me about dark patterns. The community aspect and reward points make it fun to contribute too!</p>
            <div class="testimonial-author">
                <img src="{% static 'https://media.licdn.com/dms/image/v2/D5603AQFz9vCras86Sw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1712070916942?e=1728518400&v=beta&t=ApYPKtnAgE1tgp9PBavhxehMXYMjMnS68Dn5VZa3HSs' %}" alt="Ankit Negi">
                <h3>Ankit Negi</h3>
                <div class="social-icons">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
        <div class="testimonial-card">
            <i class="fas fa-quote-left"></i>
            <p>The overall experience was very well and userfriendly, I got to know about what dark patter is and their all categories. CogniGaurd detects the dark pattern correctly, but sometimes get confused</p>
            <div class="testimonial-author">
                <img src="{% static 'https://avatars.githubusercontent.com/u/148576891?v=4' %}" alt="Dharmesh Tanwar">
                <h3>Dharmesh</h3>
                <div class="social-icons">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
        <div class="testimonial-card">
            <i class="fas fa-quote-left"></i>
            <p>I am very happy that such extension exist for detecting darkpatterns, this is because we sometimes really get confused about any message is considered as dark pattern or not, but it clear all my boubts and also teaches very well</p>
            <div class="testimonial-author">
                <img src="{% static 'https://media.licdn.com/dms/image/v2/D5603AQE8M4nseTycKg/profile-displayphoto-shrink_100_100/profile-displayphoto-shrink_100_100/0/1702703401215?e=1728518400&v=beta&t=V67g2MiuH9Lx82WlUa6ETYXH60PtIUn7WwZzjf4J9VI' %}" alt="ganesh singh">
                <h3>Ganesh Singh</h3>
                <div class="social-icons">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div id="animated-shapes">
      <div class="shape-testimon"></div>
      <div class="shape-testimon"></div>
      <div class="shape-testimon"></div>
      <div class="shape-testimon"></div>
    </div>
</section>

</section>
{% endblock content %}


{% block script %}
<script src="{% static 'js/messages.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock script %}

django-web-app/templates/login.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">

{% block head %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% comment %} <link rel="stylesheet" href="{% static 'css/responsive.css' %}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<title>CogniGuard |Login {% block title %}{% endblock title %}</title>

{% endblock head %}

{% comment %} {% block title %} Login {% endblock title %} {% endcomment %}

{% block main %}
<div class="mainContainer">

    {% include 'messages.html' %}

    <div class="mc-div">
        <div class="sub-c">
        
            <div class="sub-c-1">
                <h1 class="head">Login</h1>
                <div class="form">
                    
                    <form id="my-form" method="post" action="/login/">
                        {% csrf_token %}
                        
                        <div class="form-c-1">
                            <label class="sub-head" for="username">
                                Username
                            </label>
                            <input class="form-f" id="username" name="username" required placeholder="Type your username" type="text">
                        </div>
    

                        <div class="form-c-1">
                            <label class="sub-head" for="password">
                                Password
                            </label>

                            <div class="password-container">
                                <input class="form-f" id="password" name="password" placeholder="Type your Password" type="password" required>
                                <i class="eye-icon" id="togglePassword" onclick="togglePasswordVisibility()">👁️</i>
                            </div>

                        </div>
                        
                    </form>
                    <h4 id="forgot"> <a href="{% url 'home:password_reset' %}">Forgot password?</a></h4>
                    
                    <button id="login-btn" class="login-btn">LOGIN</button>

                    {% comment %} <a href="{% provider_login_url 'google' %}">Login with Google</a> {% endcomment %}
    
                </div>
                <div class="sign-up">
                    <p>By signing in you agree to our <a style="color: var(--color-primary);" href="{% url "home:privacy-policy" %}">privacy policy</a> and <a style="color: var(--color-primary);" href="{% url "home:terms-of-use" %}">terms of use</a>. </p>
                    Don't have an account? <span> <a href="{% url 'home:registerUser' %}">Register</a></span>!
                </div>
            </div>
        </div>
        <div class="login-img-box">
            <img src="{% static 'img/login.webp' %}" alt="Login Image CogniGuard">
        </div> 
    </div>
</div>
{% endblock main %}

{% block script %}
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/login.js' %}"></script>
<script src="{% static 'js/messages.js' %}"></script>

{% endblock script %}

django-web-app/templates/messages.html
{% if messages %}
    <ul id="message-list">
        {% for message in messages %}
            <li class="message {{ message.tags }}">
                {{ message }}
                <span class="close">&times;</span>
            </li>
        {% endfor %}
    </ul>
{% endif %}

django-web-app/templates/password_reset_complete.html
{% extends "base.html" %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static "css/password_reset_complete.css" %}">

{% endblock head%}


{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'home:loginUser' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

django-web-app/templates/password_reset_email.html
{% autoescape off %}

  To initiate the password reset process for your {{ user.email }} CogniGuard App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  Team CogniGuard💗
{% endautoescape %}

django-web-app/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% comment %} {% block title %} Register {% endblock title %} {% endcomment %}

{% block head %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% comment %} <link rel="stylesheet" href="{% static 'css/responsive.css' %}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
<title>CogniGuard |Register {% block title %}{% endblock title %}</title>

{% endblock head %}

{% block main %}
<div class="mainContainer">
   
 
    {% include 'messages.html' %}
    <div class="mc-div">
        <div class="sub-c">
        
            <div class="sub-c-1">
                <h1 class="head">Register</h1>
                <div class="form">
                    <form id="my-form" method="post" action="/register/">
                        {% csrf_token %}
                        
                        <div class="form-c-1">
                            <label class="sub-head" for="username">
                                Username
                            </label>
                            <!-- <img class="input-img" src="/static/img/user2.png" alt="user"> -->
<!--                             <i class='bx bxs-user input-img'></i> -->
                            <input class="form-f" id="username" name="username" placeholder="Username"  required  type="text">
                            
                        </div>
                        <!-- <div id="flname" class="form-c-1">
                        
                            <input class="form-f" id="firstnamae" name="firstname" placeholder="First Name"  required  type="text">
                    
                            <input class="form-f" id="lastname" name="lastname" placeholder="Last Name"  type="text">
                            
                        </div> -->
                        <div class="form-c-1">
                            <label class="sub-head" for="email">
                                Email
                            </label>
                            <!-- <img class="input-img" src="/static/img/email.png" alt="user"> -->
<!--                             <i class='bx bxs-envelope input-img'></i> -->
    
                            <input class="form-f" id="email" name="email" placeholder="example@email.com" required  type="email">
                            
                        </div>
                        
    
                        <div class="form-c-1">
                            <label class="sub-head" for="password">
                                Password
                            </label>
                            <div class="password-container">
                                <input class="form-f" id="password" name="password" placeholder="Type your Password" type="password" required>
                                <i class="eye-icon" id="eye-icon-one">👁️</i>
                            </div>
                        </div>
                        
                        <div class="form-c-1">
                            <label class="sub-head" for="cnf-password">
                                Confirm Password
                            </label>
                            <div class="password-container">
                                <input class="form-f" id="cnf-password" name="cnf-password" placeholder="Confirm your password" type="password" required>
                                <i class="eye-icon" id="eye-icon-two">👁️</i>
                            </div>
                        </div>
                        
                        
                        
                        <p style=" font-size:14px; font-family: var(--font-secondary);" > <i style="font-size: 14px;" class='bx bx-mail-send'></i> Please provide valid Email address. Email verification is required.</p>
    
                        
                    </form>
                    <!-- <h4 id="forgot"> <a href="#">By clicking you agree Terms & Conditions. </a></h4> -->
    
                    <button id="signup-btn" class="signup-btn">Register</button>
    
                </div>
                <div class="login">
                    <p>By signing up you agree to our <a style="color: var(--color-primary);" href="{% url "home:privacy-policy" %}">privacy policy</a> and <a style="color: var(--color-primary);" href="{% url "home:terms-of-use" %}">terms of use</a>. </p>
                    Already have an account! <span> <a href="{% url 'home:loginUser' %}">Login</a></span>.
                </div>
            </div>
        </div>

        <div class="signup-img-box">
            <img src="{% static 'img/register.webp' %}" alt="Register CogniGuard">
        </div> 
    </div>
    

</div>
{% endblock main %}

{% block script %}
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/register.js' %}"></script>
<script src="{% static 'js/messages.js' %}"></script>
{% endblock script %}